/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type UnitCategory = 'length' | 'weight' | 'temperature' | 'volume' | 'area' | 'speed' | 'time' | 'digital' | 'currency';

export interface Unit {
  id: string;
  name: string;
  symbol: string;
  factor: number; // Factor to convert to base unit
  offset?: number; // For temperature (Celsius is base)
}

export interface ConversionResult {
  from: string;
  to: string;
  value: number;
  result: number;
  timestamp: number;
}

export interface Language {
  code: string;
  name: string;
  dir: 'ltr' | 'rtl';
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', dir: 'ltr' },
  { code: 'ar', name: 'العربية', dir: 'rtl' },
  { code: 'es', name: 'Español', dir: 'ltr' },
  { code: 'fr', name: 'Français', dir: 'ltr' },
  { code: 'de', name: 'Deutsch', dir: 'ltr' },
  { code: 'it', name: 'Italiano', dir: 'ltr' },
  { code: 'pt', name: 'Português', dir: 'ltr' },
  { code: 'ru', name: 'Русский', dir: 'ltr' },
  { code: 'ja', name: '日本語', dir: 'ltr' },
  { code: 'ko', name: '한국어', dir: 'ltr' },
  { code: 'zh', name: '中文', dir: 'ltr' },
  { code: 'hi', name: 'हिन्दी', dir: 'ltr' },
  { code: 'tr', name: 'Türkçe', dir: 'ltr' },
  { code: 'nl', name: 'Nederlands', dir: 'ltr' },
  { code: 'sv', name: 'Svenska', dir: 'ltr' },
  { code: 'id', name: 'Bahasa Indonesia', dir: 'ltr' },
  { code: 'vi', name: 'Tiếng Việt', dir: 'ltr' },
  { code: 'th', name: 'ไทย', dir: 'ltr' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    title: 'OmniConverter',
    length: 'Length',
    weight: 'Weight',
    temperature: 'Temperature',
    volume: 'Volume',
    area: 'Area',
    speed: 'Speed',
    time: 'Time',
    digital: 'Digital Storage',
    currency: 'Currency',
    from: 'From',
    to: 'To',
    value: 'Value',
    convert: 'Convert',
    recent: 'Recent Conversions',
    favorites: 'Favorites',
    settings: 'Settings',
    language: 'Language',
    noRecent: 'No recent conversions yet',
    noFavorites: 'No favorites added yet',
    swap: 'Swap Units',
    clear: 'Clear',
    description: 'The ultimate all-in-one unit and currency converter for your daily needs.',
  },
  ar: {
    title: 'أومني كونفرتر',
    length: 'الطول',
    weight: 'الوزن',
    temperature: 'الحرارة',
    volume: 'الحجم',
    area: 'المساحة',
    speed: 'السرعة',
    time: 'الوقت',
    digital: 'التخزين الرقمي',
    currency: 'العملة',
    from: 'من',
    to: 'إلى',
    value: 'القيمة',
    convert: 'تحويل',
    recent: 'التحويلات الأخيرة',
    favorites: 'المفضلة',
    settings: 'الإعدادات',
    language: 'اللغة',
    noRecent: 'لا توجد تحويلات أخيرة بعد',
    noFavorites: 'لم يتم إضافة مفضلات بعد',
    swap: 'تبديل الوحدات',
    clear: 'مسح',
    description: 'محول الوحدات والعملات الشامل لاحتياجاتك اليومية.',
  },
  es: {
    title: 'OmniConverter',
    length: 'Longitud',
    weight: 'Peso',
    temperature: 'Temperatura',
    volume: 'Volumen',
    area: 'Área',
    speed: 'Velocidad',
    time: 'Tiempo',
    digital: 'Almacenamiento',
    currency: 'Moneda',
    from: 'De',
    to: 'A',
    value: 'Valor',
    convert: 'Convertir',
    recent: 'Conversiones recientes',
    favorites: 'Favoritos',
    settings: 'Ajustes',
    language: 'Idioma',
    noRecent: 'No hay conversiones recientes',
    noFavorites: 'No hay favoritos añadidos',
    swap: 'Intercambiar unidades',
    clear: 'Limpiar',
    description: 'El convertidor de unidades y divisas definitivo para tus necesidades diarias.',
  },
  fr: {
    title: 'OmniConverter',
    length: 'Longueur',
    weight: 'Poids',
    temperature: 'Température',
    volume: 'Volume',
    area: 'Surface',
    speed: 'Vitesse',
    time: 'Temps',
    digital: 'Stockage',
    currency: 'Devise',
    from: 'De',
    to: 'À',
    value: 'Valeur',
    convert: 'Convertir',
    recent: 'Conversions récentes',
    favorites: 'Favoris',
    settings: 'Paramètres',
    language: 'Langue',
    noRecent: 'Aucune conversion récente',
    noFavorites: 'Aucun favori ajouté',
    swap: 'Échanger les unités',
    clear: 'Effacer',
    description: 'Le convertisseur d\'unités et de devises ultime pour vos besoins quotidiens.',
  },
  de: {
    title: 'OmniConverter',
    length: 'Länge',
    weight: 'Gewicht',
    temperature: 'Temperatur',
    volume: 'Volumen',
    area: 'Fläche',
    speed: 'Geschwindigkeit',
    time: 'Zeit',
    digital: 'Speicher',
    currency: 'Währung',
    from: 'Von',
    to: 'Nach',
    value: 'Wert',
    convert: 'Konvertieren',
    recent: 'Letzte Konvertierungen',
    favorites: 'Favoriten',
    settings: 'Einstellungen',
    language: 'Sprache',
    noRecent: 'Noch keine Konvertierungen',
    noFavorites: 'Keine Favoriten hinzugefügt',
    swap: 'Einheiten tauschen',
    clear: 'Löschen',
    description: 'Der ultimative All-in-One-Einheiten- und Währungsumrechner für Ihren täglichen Bedarf.',
  },
  it: {
    title: 'OmniConverter',
    length: 'Lunghezza',
    weight: 'Peso',
    temperature: 'Temperatura',
    volume: 'Volume',
    area: 'Area',
    speed: 'Velocità',
    time: 'Tempo',
    digital: 'Memoria',
    currency: 'Valuta',
    from: 'Da',
    to: 'A',
    value: 'Valore',
    convert: 'Converti',
    recent: 'Conversioni recenti',
    favorites: 'Preferiti',
    settings: 'Impostazioni',
    language: 'Lingua',
    noRecent: 'Nessuna conversione recente',
    noFavorites: 'Nessun preferito aggiunto',
    swap: 'Scambia unità',
    clear: 'Cancella',
    description: 'Il convertitore di unità e valute definitivo per le tue esigenze quotidiane.',
  },
  pt: {
    title: 'OmniConverter',
    length: 'Comprimento',
    weight: 'Peso',
    temperature: 'Temperatura',
    volume: 'Volume',
    area: 'Área',
    speed: 'Velocidade',
    time: 'Tempo',
    digital: 'Armazenamento',
    currency: 'Moeda',
    from: 'De',
    to: 'Para',
    value: 'Valor',
    convert: 'Converter',
    recent: 'Conversões recentes',
    favorites: 'Favoritos',
    settings: 'Configurações',
    language: 'Idioma',
    noRecent: 'Nenhuma conversão recente',
    noFavorites: 'Nenhum favorito adicionado',
    swap: 'Trocar unidades',
    clear: 'Limpar',
    description: 'O conversor de unidades e moedas definitivo para as suas necessidades diárias.',
  },
  ru: {
    title: 'OmniConverter',
    length: 'Длина',
    weight: 'Вес',
    temperature: 'Температура',
    volume: 'Объем',
    area: 'Площадь',
    speed: 'Скорость',
    time: 'Время',
    digital: 'Память',
    currency: 'Валюта',
    from: 'Из',
    to: 'В',
    value: 'Значение',
    convert: 'Конвертировать',
    recent: 'Последние конверсии',
    favorites: 'Избранное',
    settings: 'Настройки',
    language: 'Язык',
    noRecent: 'Нет последних конверсий',
    noFavorites: 'Избранное пусто',
    swap: 'Поменять местами',
    clear: 'Очистить',
    description: 'Универсальный конвертер величин и валют для ваших повседневных нужд.',
  },
  ja: {
    title: 'OmniConverter',
    length: '長さ',
    weight: '重さ',
    temperature: '温度',
    volume: '体積',
    area: '面積',
    speed: '速度',
    time: '時間',
    digital: 'ストレージ',
    currency: '通貨',
    from: 'から',
    to: 'へ',
    value: '値',
    convert: '変換',
    recent: '履歴',
    favorites: 'お気に入り',
    settings: '設定',
    language: '言語',
    noRecent: '履歴はありません',
    noFavorites: 'お気に入りはありません',
    swap: '単位を入れ替える',
    clear: 'クリア',
    description: '日常のニーズに応える究極のオールインワン単位・通貨換算ツール。',
  },
  ko: {
    title: 'OmniConverter',
    length: '길이',
    weight: '무게',
    temperature: '온도',
    volume: '부피',
    area: '면적',
    speed: '속도',
    time: '시간',
    digital: '저장 용량',
    currency: '통화',
    from: '에서',
    to: '(으)로',
    value: '값',
    convert: '변환',
    recent: '최근 변환',
    favorites: '즐겨찾기',
    settings: '설정',
    language: '언어',
    noRecent: '최근 변환 내역이 없습니다',
    noFavorites: '즐겨찾기가 없습니다',
    swap: '단위 교체',
    clear: '지우기',
    description: '일상 생활에 필요한 최고의 올인원 단위 및 통화 변환기.',
  },
  zh: {
    title: 'OmniConverter',
    length: '长度',
    weight: '重量',
    temperature: '温度',
    volume: '体积',
    area: '面积',
    speed: '速度',
    time: '时间',
    digital: '数字存储',
    currency: '货币',
    from: '从',
    to: '到',
    value: '数值',
    convert: '转换',
    recent: '最近转换',
    favorites: '收藏夹',
    settings: '设置',
    language: '语言',
    noRecent: '暂无最近转换',
    noFavorites: '暂无收藏',
    swap: '交换单位',
    clear: '清除',
    description: '满足您日常需求的终极多合一单位和货币转换器。',
  },
  hi: {
    title: 'ओम्नी कनवर्टर',
    length: 'लंबाई',
    weight: 'वजन',
    temperature: 'तापमान',
    volume: 'आयतन',
    area: 'क्षेत्रफल',
    speed: 'गति',
    time: 'समय',
    digital: 'डिजिटल स्टोरेज',
    currency: 'मुद्रा',
    from: 'से',
    to: 'तक',
    value: 'मान',
    convert: 'बदलें',
    recent: 'हाल के रूपांतरण',
    favorites: 'पसंदीदा',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    noRecent: 'अभी तक कोई हालिया रूपांतरण नहीं',
    noFavorites: 'कोई पसंदीदा नहीं जोड़ा गया',
    swap: 'इकाइयां बदलें',
    clear: 'साफ़ करें',
    description: 'आपकी दैनिक आवश्यकताओं के लिए अंतिम ऑल-इन-वन इकाई और मुद्रा परिवर्तक।',
  },
  tr: {
    title: 'OmniConverter',
    length: 'Uzunluk',
    weight: 'Ağırlık',
    temperature: 'Sıcaklık',
    volume: 'Hacim',
    area: 'Alan',
    speed: 'Hız',
    time: 'Zaman',
    digital: 'Dijital Depolama',
    currency: 'Para Birimi',
    from: 'Kimden',
    to: 'Kime',
    value: 'Değer',
    convert: 'Dönüştür',
    recent: 'Son Dönüşümler',
    favorites: 'Favoriler',
    settings: 'Ayarlar',
    language: 'Dil',
    noRecent: 'Henüz son dönüşüm yok',
    noFavorites: 'Henüz favori eklenmedi',
    swap: 'Birimleri Değiştir',
    clear: 'Temizle',
    description: 'Günlük ihtiyaçlarınız için nihai hepsi bir arada birim ve para birimi dönüştürücü.',
  },
  nl: {
    title: 'OmniConverter',
    length: 'Lengte',
    weight: 'Gewicht',
    temperature: 'Temperatuur',
    volume: 'Volume',
    area: 'Oppervlakte',
    speed: 'Snelheid',
    time: 'Tijd',
    digital: 'Digitale Opslag',
    currency: 'Valuta',
    from: 'Van',
    to: 'Naar',
    value: 'Waarde',
    convert: 'Converteren',
    recent: 'Recente conversies',
    favorites: 'Favorieten',
    settings: 'Instellingen',
    language: 'Taal',
    noRecent: 'Nog geen recente conversies',
    noFavorites: 'Nog geen favorieten toegevoegd',
    swap: 'Eenheden wisselen',
    clear: 'Wissen',
    description: 'De ultieme alles-in-één eenheids- en valuta-omzetter voor uw dagelijkse behoeften.',
  },
  sv: {
    title: 'OmniConverter',
    length: 'Längd',
    weight: 'Vikt',
    temperature: 'Temperatur',
    volume: 'Volym',
    area: 'Area',
    speed: 'Hastighet',
    time: 'Tid',
    digital: 'Digital lagring',
    currency: 'Valuta',
    from: 'Från',
    to: 'Till',
    value: 'Värde',
    convert: 'Konvertera',
    recent: 'Senaste konverteringar',
    favorites: 'Favoriter',
    settings: 'Inställningar',
    language: 'Språk',
    noRecent: 'Inga senaste konverteringar än',
    noFavorites: 'Inga favoriter tillagda än',
    swap: 'Byt enheter',
    clear: 'Rensa',
    description: 'Den ultimata allt-i-ett-enhets- och valutaomvandlaren för dina dagliga behov.',
  },
  id: {
    title: 'OmniConverter',
    length: 'Panjang',
    weight: 'Berat',
    temperature: 'Suhu',
    volume: 'Volume',
    area: 'Luas',
    speed: 'Kecepatan',
    time: 'Waktu',
    digital: 'Penyimpanan Digital',
    currency: 'Mata Uang',
    from: 'Dari',
    to: 'Ke',
    value: 'Nilai',
    convert: 'Konversi',
    recent: 'Konversi Terbaru',
    favorites: 'Favorit',
    settings: 'Pengaturan',
    language: 'Bahasa',
    noRecent: 'Belum ada konversi terbaru',
    noFavorites: 'Belum ada favorit ditambahkan',
    swap: 'Tukar Unit',
    clear: 'Hapus',
    description: 'Konverter unit dan mata uang lengkap terbaik untuk kebutuhan harian Anda.',
  },
  vi: {
    title: 'OmniConverter',
    length: 'Chiều dài',
    weight: 'Cân nặng',
    temperature: 'Nhiệt độ',
    volume: 'Thể tích',
    area: 'Diện tích',
    speed: 'Tốc độ',
    time: 'Thời gian',
    digital: 'Lưu trữ kỹ thuật số',
    currency: 'Tiền tệ',
    from: 'Từ',
    to: 'Đến',
    value: 'Giá trị',
    convert: 'Chuyển đổi',
    recent: 'Chuyển đổi gần đây',
    favorites: 'Yêu thích',
    settings: 'Cài đặt',
    language: 'Ngôn ngữ',
    noRecent: 'Chưa có chuyển đổi gần đây',
    noFavorites: 'Chưa có yêu thích nào',
    swap: 'Đổi đơn vị',
    clear: 'Xóa',
    description: 'Bộ chuyển đổi đơn vị và tiền tệ tất cả trong một tối ưu cho nhu cầu hàng ngày của bạn.',
  },
  th: {
    title: 'OmniConverter',
    length: 'ความยาว',
    weight: 'น้ำหนัก',
    temperature: 'อุณหภูมิ',
    volume: 'ปริมาตร',
    area: 'พื้นที่',
    speed: 'ความเร็ว',
    time: 'เวลา',
    digital: 'พื้นที่จัดเก็บข้อมูล',
    currency: 'สกุลเงิน',
    from: 'จาก',
    to: 'ถึง',
    value: 'ค่า',
    convert: 'แปลง',
    recent: 'การแปลงล่าสุด',
    favorites: 'รายการโปรด',
    settings: 'การตั้งค่า',
    language: 'ภาษา',
    noRecent: 'ยังไม่มีการแปลงล่าสุด',
    noFavorites: 'ยังไม่มีรายการโปรด',
    swap: 'สลับหน่วย',
    clear: 'ล้าง',
    description: 'สุดยอดเครื่องมือแปลงหน่วยและสกุลเงินแบบครบวงจรสำหรับความต้องการในแต่ละวันของคุณ',
  },
};
